### GET all inscripciones a talleres
GET http://localhost:3000/api/inscripcion-taller

### GET by ID
GET http://localhost:3000/api/inscripcion-taller/1

### Create inscripcion a taller
POST http://localhost:3000/api/inscripcion-taller
Content-Type: application/json

{
  "campista": 4,
  "taller": 1,
  "fechaInscripcion": "2025-09-01T10:00:00Z",
  "estado": "pendiente"
}

### Create inscripcion a taller 2
POST http://localhost:3000/api/inscripcion-taller
Content-Type: application/json

{
  "campista": 2,
  "taller": 1,
  "fechaInscripcion": "2025-09-02T10:00:00Z",
  "estado": "pendiente"
}
