### GET all talleres
GET http://localhost:3000/api/talleres

### GET by ID
GET http://localhost:3000/api/talleres/1

### Create Taller
POST http://localhost:3000/api/talleres
Content-Type: application/json

{
  "titulo": "Taller de RCP",
  "descripcion": "Aprende a actuar ante una urgencia y se el heroe.",
  "fechaHora": "2025-10-01T10:00:00Z",
  "lugar": "Zona 8: La cueva de los héroes",
  "instructor": 1
}

### Create Taller 2
POST http://localhost:3000/api/talleres
Content-Type: application/json
{
  "titulo": "Taller de Supervivencia",
  "descripcion": "Aprende a sobrevivir en la naturaleza.",
  "fechaHora": "2025-10-02T10:00:00Z",
  "lugar": "Zona 3: El bosque encantado",
  "instructor": 2
}