### GET all characters
GET http://localhost:3000/api/admin
Content-Type: application/json
Cookie: token={{tokenadmin}}

### GET by ID
GET http://localhost:3000/api/admin/1
Content-Type: application/json
Cookie: token={{tokenadmin}}

### Create Admin
POST http://localhost:3000/api/admin
Content-Type: application/json
Cookie: token={{tokenadmin}}
{
  "nombre": "Luke",
  "apellido": "Castellan",
  "email": "lukecastenllan@gmail.com",
  "telefono": "123456789",
  "contrasena": "123456",
  "fechaNac": "1920-01-01T00:00:00.000Z",
  "direccion": "3141 Farmroad",
  "alergias": "Ninguna",
  "grupoSanguineo": "O",
  "rh": "+"
}

### Create admin  2
POST http://localhost:3000/api/admin
Content-Type: application/json
Cookie: token={{tokenadmin}}

{
  "nombre": "Dionisio",
  "apellido": "God",
  "email": "directorgeneralseñord@gmail.com",
  "nick": "SeñorD",
  "contrasena": "123456",
  "fechaNac": "1924-01-01T00:00:00.000Z",
  "direccion": "3141 Farmroad",
  "alergias": "Ninguna",
  "grupoSanguineo": "O+"
}


### update admin
PATCH  http://localhost:3000/api/admin/1
Content-Type: application/json
Cookie: token={{tokenadmin}}

{
  "verificationToken": null,
  "isVerified": true
}