### GET all asignaciones a misiones
GET http://localhost:3000/api/asigna-mision
Content-Type: application/json
Cookie: token={{tokenadmin}}

### GET by ID
GET http://localhost:3000/api/asigna-mision/3
Content-Type: application/json
Cookie: token={{tokencampista}}

### Create asignacion a mision
POST http://localhost:3000/api/asigna-mision
Content-Type: application/json
Cookie: token={{tokeninstructor}}

{
  "campista": 1,
  "mision": 18,
  "estado": "asignada",
  "periodo": 1
}

### Create asignacion a mision 2
POST http://localhost:3000/api/asigna-mision
Content-Type: application/json
Cookie: token={{tokencampista}}

{
  "campista": 4,
  "mision": 2,
  "estado": "asignada"
}