### Obtener todas las deidades
GET http://localhost:3000/api/deidades
Content-Type: application/json
Cookie: token={{tokenadmin}}

### Obtener por ID
GET http://localhost:3000/api/deidades/1
Content-Type: application/json
Cookie: token={{tokenadmin}}

### Crear deidad 1
POST http://localhost:3000/api/deidades
Content-Type: application/json
Cookie: token={{tokenadmin}}

{
  "nombre": "Zeus",
  "descripcion": "Dios del cielo y el trueno, rey de los dioses en la mitología griega.",
  "lema": "Poder y justicia",
  "simbolo": "Rayo"
}

### Crear deidad 2
POST http://localhost:3000/api/deidades
Content-Type: application/json
Cookie: token={{tokencampista}}

{
  "nombre": "Athena",
  "descripcion": "Diosa de la sabiduría, la guerra y las artes en la mitología griega.",
  "lema": "Sabiduría y estrategia",
  "simbolo": "Búho"
}

### Crear deidad 3
POST http://localhost:3000/api/deidades
Content-Type: application/json
Cookie: token={{tokencampista}}

{
  "nombre": "Hades",
  "descripcion": "Dios del inframundo y los muertos en la mitología griega.",
  "lema": "El guardián de las almas",
  "simbolo": "Casco de invisibilidad"
}

### Crear deidad 4
POST http://localhost:3000/api/deidades
Content-Type: application/json
Cookie: token={{tokenadmin}}

{
  "nombre": "Apolo",
  "descripcion": "Dios del sol, la música, la poesía, la profecía y la medicina en la mitología griega.",
  "lema": "Armonía y luz",
  "simbolo": "Lira y laurel"
}



