### Obtener todas las hospedajes
GET http://localhost:3000/api/hospedaje
### Obtener por ID
GET http://localhost:3000/api/hospedaje/1

### Crear Hospedaje 1
POST http://localhost:3000/api/hospedaje
Content-Type: application/json

{
  "cabania": 1,
  "campista": 4,
  "fechaInicio": "2023-10-01T12:00:00Z",
  "estado": "reservada"
}

### Crear Hospedaje 2
POST http://localhost:3000/api/hospedaje
Content-Type: application/json

{
  "cabania": 2,
  "campista": 2,
  "fechaInicio": "2023-10-02T12:00:00Z",
  "estado": "reservada"
}

### Crear Hospedaje 3
POST http://localhost:3000/api/hospedaje
Content-Type: application/json

{
  "cabania": 3,
  "campista": 3,
  "fechaInicio": "2023-10-03T12:00:00Z",
  "estado": "reservada"
}