### GET all misiones
GET http://localhost:3000/api/inscripcion-periodo
Content-Type: application/json
Cookie: 


### GET by ID
GET http://localhost:3000/api/inscripcion-periodo/1

### Create Mision
POST http://localhost:3000/api/inscripcion-periodo
Content-Type: application/json

{
  "campista": 14,
  "periodo": 1,
  "metodoPago": "TRANSFERENCIA",
  "referenciaPago": "ABC123XYZ",
  "estado": "PENDIENTE"
}