### GET all instructores
GET http://localhost:3000/api/instructor
Content-Type: application/json
Cookie: token={{tokencampista}}

### GET all instructores
GET http://localhost:3000/api/instructor
Content-Type: application/json
Cookie: token={{tokeninstructor}}

### GET by ID
GET http://localhost:3000/api/instructor/1
Content-Type: application/json
Cookie: token={{tokencampista}}

### GET by ID
GET http://localhost:3000/api/instructor/1
Content-Type: application/json
Cookie: token={{tokeninstructor}}

### Create Instructor
POST http://localhost:3000/api/instructor
Content-Type: application/json
Cookie: token={{tokenadmin}}

{
  "nombre": "Jorge",
  "apellido": "Sanchez",
  "email": "jorguesanchez@gmail.com",
  "telefono":"+543515888485",
  "contrasena": "jorge1234",
  "fechaNac": "1996-10-05T00:00:00.000Z",
  "pais":"Argentina",
  "ciudad":"Rosario",
  "direccion": "Calle Falsa 123, Chaco",
  "alergias": "Mani",
  "grupoSanguineo": "AB+",
  "especialidad": "Supervivencia",
  "nivel": 1
}

### Create Instructor 2
POST http://localhost:3000/api/instructor
Content-Type: application/json
Cookie: token={{tokenadmin}}

{
  "nombre": "Laura",
  "apellido": "Perez",
  "email": "lauperez85@gmail.com",
  "telefono":"+543515866485",
  "contrasena": "lau1234",
  "fechaNac": "1990-08-20T00:00:00.000Z",
  "pais":"Argentina",
  "ciudad":"Rosario",
  "direccion": "Avenida Siempre Viva 456",
  "alergias": "Ninguna",
  "grupoSanguineo": "O-",
  "especialidad": "Primeros Auxilios",
  "nivel": 2
}
