### GET all misiones
GET http://localhost:3000/api/misiones
Content-Type: application/json
Cookie: token={{tokencampista}}

### GET all misiones
GET http://localhost:3000/api/misiones
Content-Type: application/json
Cookie: token={{tokeninstructor}}

### GET by ID
GET http://localhost:3000/api/misiones/1
Content-Type: application/json
Cookie: token={{tokencampista}}

### GET by ID
GET http://localhost:3000/api/misiones/1
Content-Type: application/json
Cookie: token={{tokeninstructor}}

### Create Mision
POST http://localhost:3000/api/misiones
Content-Type: application/json
Cookie: token={{tokenadmin}}

{
  "titulo": "Caza del tesoro",
  "descripcion": "Hay un gran tesoro escondido en el campamento. Encuentralo!",
  "recompensa": "Una barra de chocolate",
  "pista": "Busca en el lago, sobre la roca más grande"
}

### Create Mision 2
POST http://localhost:3000/api/misiones
Content-Type: application/json
Cookie: token={{tokenadmin}}

{
  "titulo": "Descubre la cueva de las hadas",
  "descripcion": "Se dice que hay una cueva mágica donde viven las hadas. Encuéntrala y habla con ellas.",
  "recompensa": "Espada de madera mágica",
  "pista": "Sigue el sendero de flores rosas ubicado al este del campamento"
}
