### GET all talleres
GET http://localhost:3000/api/talleres
Content-Type: application/json
Cookie: token={{tokenadmin}}

### GET all talleres
GET http://localhost:3000/api/talleres
Content-Type: application/json
Cookie: token={{tokencampista}}

### GET by ID
GET http://localhost:3000/api/talleres/1
Content-Type: application/json
Cookie: token={{tokenadmin}}

### Create Taller
POST http://localhost:3000/api/talleres
Content-Type: application/json
Cookie: token={{tokenadmin}}

{
  "titulo": "Taller de Manualidades",
  "descripcion": "Aprende a hacer manualidades con materiales reciclados.",
  "fechaHora": "2025-10-01T10:00:00.000Z",
  "lugar": "Zona 2: El rincón creativo",
  "instructor": 1,
  "cupo": 15,
  "duracionMin": 90,
  "periodo": 2
}

### Create Taller 2
POST http://localhost:3000/api/talleres
Content-Type: application/json
Cookie: token={{tokenadmin}}

{
  "titulo": "Taller de Supervivencia",
  "descripcion": "Aprende a sobrevivir en la naturaleza.",
  "fechaHora": "2025-10-02T10:00:00Z",
  "lugar": "Zona 3: El bosque encantado",
  "instructor": 2
}

### Create Taller 3
POST http://localhost:3000/api/talleres
Content-Type: application/json
Cookie: token={{tokenadmin}}

{
  "titulo": "Taller de Primeros Auxilios",
  "descripcion": "Aprende a brindar primeros auxilios en situaciones de emergencia.",
  "fechaHora": "2025-10-03T10:00:00Z",
  "lugar": "Zona 5: La clínica móvil",
  "instructor": 1
}

### actualizar taller
PATCH http://localhost:3000/api/talleres/2
Content-Type: application/json
Cookie: token={{tokenadmin}}

{
    "estado": "cerrado"
}